Ch s/v2/prices component
JanAsaulenko/coworking pull request #39
Opened 2018-09-27 16:58 UTC by SuppressorButtons

Was fully implemented prices.component. Repaired source and links for images(v2/src/assets/images)

2018-09-28 08:25 UTC, AlexOrd requested changes

2018-09-28 08:25 UTC, AlexOrd commented on v2/src/app/components/prices/prices.component.ts
> +            // ...price, // WTF ????? //todo Should ask Aleksandr
TODO: Investigate price visualization.

2018-09-28 08:25 UTC, AlexOrd commented on v2/src/app/services/prices.service.ts
> +    // return [{ marker: { lat: 49.229065, long: 28.425729} }]
Unnecessary comments.

2018-09-28 12:28 UTC, SuppressorButtons reviewed
Problem with npm settings

2018-09-29 13:17 UTC, bedTooTheBone commented
Please merged this .... I waiting this ... I suhd use some portion of this component and application settings.

2018-09-29 19:46 UTC, merged